FROM amazoncorretto:11-alpine-jdk
MAINTAINER akibandali@gmail.com
COPY target/recipes-search-service-0.0.1-SNAPSHOT.jar recipes-search-service.jar
ENTRYPOINT ["java","-jar","/recipes-search-service.jar"]
