FROM amazoncorretto:11-alpine-jdk
MAINTAINER akibandali@gmail.com
COPY target/recipe-search-consumer-service-0.0.1-SNAPSHOT.jar recipe-search-consumer-service.jar
ENTRYPOINT ["java","-jar","/recipe-search-consumer-service.jar"]
